"""
Quality gate tests (cultureQC_upgrade.md §5.2, §5.5 acceptance: "blurred,
dark, uneven images fail"). Runs on CPU, no GPU, no cache dependency for the
synthetic cases — only the real-tile cases below need configs/quality.yaml
(generated by scripts/calibrate_quality_gate.py; already committed).
"""

from __future__ import annotations

import os

import cv2
import numpy as np
import pytest

from culture.quality import quality_gate

TEST_DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "test-data")


def _clean_tile(size=256, seed=0) -> np.ndarray:
    """A synthetic 'normal' tile: mid-grey with mild texture, no artifacts —
    should comfortably pass all three checks."""
    rng = np.random.default_rng(seed)
    img = np.full((size, size), 128, dtype=np.float32)
    img += rng.normal(0, 6, (size, size))  # texture, not noise-dominated
    # a few sharp synthetic "cell" edges so blur isn't near-zero
    for _ in range(15):
        cy, cx = rng.integers(20, size - 20, 2)
        r = rng.integers(5, 15)
        cv2.circle(img, (cx, cy), r, float(rng.uniform(90, 160)), -1)
    # Real "normal" tiles' exposure_mean is extremely tight (127.79-129.22,
    # calibrated from 1000 real samples, std 0.26) -- texture/circles above
    # easily drift the mean outside that band even though nothing is
    # actually wrong with the image, so recentre exactly onto the middle of
    # the calibrated band. This isolates "is content actually blurred/dark/
    # bright/uneven" from "did my synthetic construction happen to also
    # shift the mean," which is what the other tests below want to test.
    img = img - img.mean() + 128.5
    return np.clip(img, 0, 255).astype(np.uint8)


def test_clean_tile_passes():
    img = _clean_tile()
    result = quality_gate(img)
    assert result.passed, f"clean synthetic tile failed: {result.reasons}"
    assert result.reasons == []


def test_blurred_image_fails():
    img = _clean_tile()
    blurred = cv2.GaussianBlur(img, (31, 31), sigmaX=12)
    result = quality_gate(blurred)
    assert not result.passed
    assert "blur_below_threshold" in result.reasons


def test_dark_image_fails():
    img = _clean_tile()
    dark = np.clip(img.astype(np.float32) * 0.3, 0, 255).astype(np.uint8)
    result = quality_gate(dark)
    assert not result.passed
    assert "exposure_out_of_range" in result.reasons


def test_bright_image_fails():
    img = _clean_tile()
    bright = np.clip(img.astype(np.float32) * 1.8 + 60, 0, 255).astype(np.uint8)
    result = quality_gate(bright)
    assert not result.passed
    assert "exposure_out_of_range" in result.reasons


def test_uneven_illumination_fails():
    img = _clean_tile().astype(np.float32)
    h, w = img.shape
    yy, xx = np.mgrid[0:h, 0:w]
    # strong linear illumination gradient across the tile
    gradient = (xx / w) * 90 - 45
    uneven = np.clip(img + gradient, 0, 255).astype(np.uint8)
    result = quality_gate(uneven)
    assert not result.passed
    assert "uniformity_above_threshold" in result.reasons


@pytest.mark.skipif(not os.path.exists(os.path.join(TEST_DATA, "normal_00005.png")), reason="fixture missing")
def test_real_normal_tile_passes():
    img = cv2.imread(os.path.join(TEST_DATA, "normal_00005.png"), cv2.IMREAD_GRAYSCALE)
    result = quality_gate(img)
    assert result.passed, f"real normal fixture failed: {result.reasons}"


def test_image_quality_tile_sample_recall_matches_calibration():
    """The gate's union-of-3-checks recall on data/tiles/'s 'image_quality'
    class is ~72% overall (configs/quality.yaml) -- not 100%, since that
    class bundles several distinct defect types and not all of them move
    these three metrics. Checked directly against a real sample rather than
    assuming any single fixture (including the one shipped in test-data/)
    must fail -- it may legitimately be in the ~28% these checks don't
    catch, which is a real, already-measured property of the gate, not a
    bug to assert around."""
    import pandas as pd

    tiles_dir = os.path.join(TEST_DATA, "..", "data", "tiles")
    manifest_path = os.path.join(tiles_dir, "manifest.csv")
    if not os.path.exists(manifest_path):
        pytest.skip("data/tiles/ not present locally")

    manifest = pd.read_csv(manifest_path)
    sample = manifest[manifest["class"] == "image_quality"].sample(100, random_state=0)
    n_fail = 0
    for _, row in sample.iterrows():
        path = os.path.join(tiles_dir, row["class"], row["tile_id"])
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue
        if not quality_gate(img).passed:
            n_fail += 1
    recall = n_fail / len(sample)
    # 72% +/- a wide band for sampling noise on n=100 vs. the full n=1000
    # calibration run -- this is a regression guard (did something silently
    # break the gate/thresholds), not a tight statistical claim.
    assert 0.55 <= recall <= 0.90, f"recall {recall:.2f} drifted far from the calibrated ~0.72"
