"""
Quality gate tests (cultureQC_upgrade.md §5.2, §5.5 acceptance: "blurred,
dark, uneven images fail"). Runs on CPU, no GPU, no cache dependency for the
synthetic cases — only the real-tile cases below need configs/quality.yaml
(generated by scripts/calibrate_quality_gate.py; already committed).
"""

from __future__ import annotations

import os

import cv2
import numpy as np
import pytest

from culture.quality import quality_gate

TEST_DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "test-data")


def _clean_tile(size=256, seed=0) -> np.ndarray:
    """A synthetic 'normal' tile: mid-grey with mild texture, no artifacts —
    should comfortably pass all three checks."""
    rng = np.random.default_rng(seed)
    img = np.full((size, size), 128, dtype=np.float32)
    img += rng.normal(0, 6, (size, size))  # texture, not noise-dominated
    # a few sharp synthetic "cell" edges so blur isn't near-zero
    for _ in range(15):
        cy, cx = rng.integers(20, size - 20, 2)
        r = rng.integers(5, 15)
        cv2.circle(img, (cx, cy), r, float(rng.uniform(90, 160)), -1)
    # Real "normal" tiles' exposure_mean is extremely tight (127.79-129.22,
    # calibrated from 1000 real samples, std 0.26) -- texture/circles above
    # easily drift the mean outside that band even though nothing is
    # actually wrong with the image, so recentre exactly onto the middle of
    # the calibrated band. This isolates "is content actually blurred/dark/
    # bright/uneven" from "did my synthetic construction happen to also
    # shift the mean," which is what the other tests below want to test.
    img = img - img.mean() + 128.5
    return np.clip(img, 0, 255).astype(np.uint8)


def test_clean_tile_passes():
    img = _clean_tile()
    result = quality_gate(img)
    assert result.passed, f"clean synthetic tile failed: {result.reasons}"
    assert result.reasons == []


def test_blurred_image_fails():
    img = _clean_tile()
    blurred = cv2.GaussianBlur(img, (31, 31), sigmaX=12)
    result = quality_gate(blurred)
    assert not result.passed
    assert "blur_below_threshold" in result.reasons


def test_dark_image_fails():
    img = _clean_tile()
    dark = np.clip(img.astype(np.float32) * 0.3, 0, 255).astype(np.uint8)
    result = quality_gate(dark)
    assert not result.passed
    assert "exposure_out_of_range" in result.reasons


def test_bright_image_fails():
    img = _clean_tile()
    bright = np.clip(img.astype(np.float32) * 1.8 + 60, 0, 255).astype(np.uint8)
    result = quality_gate(bright)
    assert not result.passed
    assert "exposure_out_of_range" in result.reasons


def test_uneven_illumination_fails():
    img = _clean_tile().astype(np.float32)
    h, w = img.shape
    yy, xx = np.mgrid[0:h, 0:w]
    # strong linear illumination gradient across the tile
    gradient = (xx / w) * 90 - 45
    uneven = np.clip(img + gradient, 0, 255).astype(np.uint8)
    result = quality_gate(uneven)
    assert not result.passed
    assert "uniformity_above_threshold" in result.reasons


@pytest.mark.skipif(not os.path.exists(os.path.join(TEST_DATA, "normal_00005.png")), reason="fixture missing")
def test_real_normal_tile_passes():
    img = cv2.imread(os.path.join(TEST_DATA, "normal_00005.png"), cv2.IMREAD_GRAYSCALE)
    result = quality_gate(img)
    assert result.passed, f"real normal fixture failed: {result.reasons}"


def test_image_quality_tile_sample_recall_matches_calibration():
    """The gate's union-of-3-checks recall on data/tiles/'s 'image_quality'
    class is ~72% overall (configs/quality.yaml) -- not 100%, since that
    class bundles several distinct defect types and not all of them move
    these three metrics. Checked directly against a real sample rather than
    assuming any single fixture (including the one shipped in test-data/)
    must fail -- it may legitimately be in the ~28% these checks don't
    catch, which is a real, already-measured property of the gate, not a
    bug to assert around."""
    import pandas as pd

    tiles_dir = os.path.join(TEST_DATA, "..", "data", "tiles")
    manifest_path = os.path.join(tiles_dir, "manifest.csv")
    if not os.path.exists(manifest_path):
        pytest.skip("data/tiles/ not present locally")

    manifest = pd.read_csv(manifest_path)
    sample = manifest[manifest["class"] == "image_quality"].sample(100, random_state=0)
    n_fail = 0
    for _, row in sample.iterrows():
        path = os.path.join(tiles_dir, row["class"], row["tile_id"])
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue
        if not quality_gate(img).passed:
            n_fail += 1
    recall = n_fail / len(sample)
    # 72% +/- a wide band for sampling noise on n=100 vs. the full n=1000
    # calibration run -- this is a regression guard (did something silently
    # break the gate/thresholds), not a tight statistical claim.
    assert 0.55 <= recall <= 0.90, f"recall {recall:.2f} drifted far from the calibrated ~0.72"


# -- per-dataset threshold entries (configs/quality.yaml `entries`) --

def test_dataset_entry_thresholds_are_used_only_for_that_dataset(tmp_path):
    import yaml

    from culture.quality import evaluate_thresholds
    cfg = {"blur_laplacian_var": {"floor": 100.0}, "exposure_mean": {"low": 127.0, "high": 129.0},
           "uniformity_block_std": {"ceiling": 2.0},
           "entries": {"real": {"datasets": ["c2c12"], "blur_laplacian_var": {"floor": 40.0},
                                "exposure_mean": {"low": 90.0, "high": 150.0},
                                "uniformity_block_std": {"ceiling": 25.0}}}}
    path = tmp_path / "quality.yaml"
    path.write_text(yaml.safe_dump(cfg))
    real = evaluate_thresholds(60.0, 110.0, 12.0, config_path=str(path), dataset="c2c12")
    assert real.passed and real.thresholds == "real" and real.to_dict()["thresholds"] == "real"
    for ds in (None, "evican_eval2019"):
        r = evaluate_thresholds(60.0, 110.0, 12.0, config_path=str(path), dataset=ds)
        assert not r.passed and r.thresholds == "default"
        assert set(r.reasons) == {"blur_below_threshold", "exposure_out_of_range", "uniformity_above_threshold"}


def test_calibrate_entry_keeps_top_level_and_uses_tuning_frames_only(tmp_path, monkeypatch):
    import importlib.util
    import sys

    import pandas as pd
    import yaml
    spec = importlib.util.spec_from_file_location(
        "calibrate_quality_gate", os.path.join(os.path.dirname(__file__), "..", "scripts", "calibrate_quality_gate.py"))
    cq = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(cq)

    cache = tmp_path / "cache"
    (cache / "sidecars").mkdir(parents=True)
    rows, q = [], []
    for k, (sid, exposure) in enumerate([("s_tune", 100.0), ("s_held", 200.0)]):
        for i in range(50):
            sha = f"{sid}_{i}"
            rows.append({"image_sha256": sha, "dataset": "c2c12", "sequence_id": sid})
            q.append({"image_sha256": sha, "blur_laplacian_var": 50.0 + i, "exposure_mean": exposure + i * 0.1,
                      "uniformity_block_std": 10.0})
    pd.DataFrame(rows).to_parquet(cache / "images.parquet")
    pd.DataFrame(q).to_parquet(cache / "quality.parquet")
    pd.DataFrame(columns=["fault_sequence_id", "base_sequence_id", "fault_type", "is_modified", "severity",
                          "image_sha256"]).astype({"is_modified": bool}).to_parquet(
        cache / "sidecars" / "fault_manifest.parquet")
    split = tmp_path / "split.csv"
    pd.DataFrame([{"sequence_id": "s_tune", "kind": "base", "split": "tuning"},
                  {"sequence_id": "s_held", "kind": "base", "split": "heldout"}]).to_csv(split, index=False)
    top = {"blur_laplacian_var": {"floor": 100.88}, "exposure_mean": {"low": 127.79, "high": 129.22},
           "uniformity_block_std": {"ceiling": 2.231}}
    out = tmp_path / "quality.yaml"
    out.write_text(yaml.safe_dump(top))

    monkeypatch.setattr(sys, "argv", ["x", "--cache-dir", str(cache), "--entry", "c2c12", "--split", str(split),
                                      "--out", str(out), "--results", str(tmp_path)])
    cq.main()
    doc = yaml.safe_load(out.read_text())
    assert {k: doc[k] for k in top} == top
    e = doc["entries"]["c2c12"]
    assert e["datasets"] == ["c2c12"] and e["calibration"]["n_sequences"] == 1
    assert 100.0 <= e["exposure_mean"]["low"] <= e["exposure_mean"]["high"] <= 105.0  # tuning frames only
    assert e["calibration"]["heldout_normal_fail_rate_pct"] == 100.0
    assert (tmp_path / "quality_gate_c2c12.md").exists()
