"""Copy the pipeline into each Space directory so it can be pushed standalone.

    python deploy/sync_space.py [--check]

A HuggingFace Space is a git repo of its own, so it has to carry `culture/` and
`config/` inside it. Keeping a second hand-maintained copy of the analysis code
is how the deployed pipeline quietly stops being the one in the repo, so those
directories are *generated* here and the repo root stays the single source of
truth. `--check` reports drift without writing, which is the useful form in CI.

There are two Spaces, both fed from the same repo root: `hf-space` (the FastAPI
backend the product frontend calls) and `hf-space-demo` (the review console,
demo/app.py, for the call day; its raw-output app.py is kept beside it).
Everything else inside each — api.py/app.py/console.py, Dockerfile,
requirements.txt, packages.txt, README.md — is hand-written and never touched
by this script.

Tracked mirrors are committed and checked by `--check` (CI). Untracked ones are
git-ignored and only written by a sync: the console's `demo/` (6 MB of
precomputed examples would otherwise be committed twice) and the 67 MB anomaly
banks, which are not in git at all (cache/anomaly/banks.npz, regenerated by
scripts/eval_anomaly.py) and reach the Space through the publish script.
"""

from __future__ import annotations

import argparse
import filecmp
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
# Space -> paths relative to ROOT, copied to the same path inside the Space.
TRACKED = {
    "hf-space": ["culture", "config", "configs"],
    "hf-space-demo": ["culture", "config", "configs"],
}
UNTRACKED = {
    "hf-space-demo": ["demo", "cache/anomaly/banks.npz"],
}
SPACES = [os.path.join(HERE, name) for name in TRACKED]
MIRRORED = sorted({p for paths in TRACKED.values() for p in paths})
SKIP = {"__pycache__", ".DS_Store", ".pytest_cache", "uploads"}


def _ignore(_dir, names):
    return [n for n in names if n in SKIP or n.endswith((".pyc", ".jsonl"))]


def _walk(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP]
        for f in filenames:
            if f in SKIP or f.endswith((".pyc", ".jsonl")):
                continue
            yield os.path.relpath(os.path.join(dirpath, f), root)


def check() -> int:
    drift = []
    for space_name, names in TRACKED.items():
        space = os.path.join(HERE, space_name)
        for name in names:
            src, dst = os.path.join(ROOT, name), os.path.join(space, name)
            rel_space = os.path.relpath(space, HERE)
            if not os.path.isdir(dst):
                drift.append(f"{rel_space}/{name}/ is missing")
                continue
            s, d = set(_walk(src)), set(_walk(dst))
            drift += [f"{rel_space}/{name}/{p} not synced" for p in sorted(s - d)]
            drift += [f"{rel_space}/{name}/{p} is stale" for p in sorted(d - s)]
            drift += [f"{rel_space}/{name}/{p} differs" for p in sorted(s & d)
                      if not filecmp.cmp(os.path.join(src, p), os.path.join(dst, p), shallow=False)]
    if drift:
        print("Spaces are out of sync with the repo:")
        for d in drift:
            print("  " + d)
        print("\nrun: python deploy/sync_space.py")
        return 1
    print(f"Spaces match the repo ({', '.join(n + '/' for n in MIRRORED)}, "
          f"{len(SPACES)} space(s))")
    return 0


def sync() -> int:
    for space_name in TRACKED:
        space = os.path.join(HERE, space_name)
        for name in TRACKED[space_name] + UNTRACKED.get(space_name, []):
            src, dst = os.path.join(ROOT, name), os.path.join(space, name)
            if os.path.isfile(src):
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copyfile(src, dst)
                print(f"  {name} -> {os.path.relpath(dst, ROOT)}  ({os.path.getsize(dst) / 1e6:.0f} MB)")
                continue
            if not os.path.isdir(src):
                if name in UNTRACKED.get(space_name, []):
                    print(f"  !! {name} not found; {space_name} will run without it", file=sys.stderr)
                    continue
                print(f"  !! {src} does not exist", file=sys.stderr)
                return 1
            shutil.rmtree(dst, ignore_errors=True)
            shutil.copytree(src, dst, ignore=_ignore)
            print(f"  {name}/ -> {os.path.relpath(dst, ROOT)}  "
                  f"({sum(1 for _ in _walk(dst))} files)")
    return 0


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="report drift instead of writing")
    a = p.parse_args()
    sys.exit(check() if a.check else sync())
