#!/usr/bin/env python3
"""
culture/growth.py backtest (cultureQC_upgrade.md §6.2).

IMPORTANT — what this backtest actually measures: real C2C12 sequences
aren't cached yet (culture/replay.py's own docstring: the real Slice 1b
cache has sequence_id/frame_idx unset for every row; nb/00 + a cache pass
that sets them haven't run). This backtest therefore runs entirely on
**synthetic, hand-generated ground-truth growth curves**, not real cell
growth. It is a **harness correctness check** — does the fit + T* +
bootstrap-interval code recover a known crossing time from a realistically
noisy, irregularly-sampled, repositioned replay stream? — not a measurement
of real prediction accuracy, and its numbers must never be quoted as the
§12 claims-policy sentence ("Predicts time to target confluency with <median
error> h ... in backtests on replayed <dataset> sequences") until re-run on
real cached C2C12/CTC sequences.

Two families of ground-truth curves, to avoid a circular "fit a logistic to
data generated by a logistic" result:
  - `on_model`: a generalized logistic with nu=1 — i.e. an exact logistic.
    An optimistic sanity ceiling, not a fair test (growth.py's own logistic
    candidate is literally the generating function).
  - `off_model`: a generalized (Richards) logistic with nu=3, asymmetric
    around its inflection — NOT one of growth.py's two candidate curves
    (logistic or Gompertz), so recovering its 80% crossing is the fairer
    check of whether either approximates an unknown real shape well enough.

For each synthetic stream: build a synthetic cache (same on-disk parquet
schema as culture.cache.Cache, same fixture-through-real-Cache pattern as
demo/flask_timeline.py and tests/test_replay.py), replay it through
culture.replay.build_replay_visits (real code path), find the first visit
reaching 40/50/60% confluency, fit culture.growth.fit_growth on the prefix
up to that visit, predict the 80% crossing, and compare to the curve's own
true (numerically solved) 80% crossing time. Repeated "with repositioning"
(larger simulated FOV/crop noise) and "without" (near-zero) per §6.2's
"shows the effect of FOV noise."

Usage:
    python scripts/backtest_growth.py [--seed 0] [--n-boot 200]
Outputs:
    results/growth_backtest.csv   — one row per (stream, reach_threshold, repositioning)
    results/growth_backtest.md    — median abs error + 90% interval coverage table
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import tempfile

import numpy as np
import pandas as pd
from scipy.optimize import brentq

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from culture.cache import Cache
from culture.growth import fit_growth
from culture.replay import build_replay_visits

RESULTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")

# A group's median/coverage isn't a meaningful summary statistic below this
# many resolved windows (one window IS one data point) -- such groups stay
# in the full CSV but are dropped from the printed/README summary table so a
# single lucky-or-unlucky sample doesn't sit next to a real distribution and
# invite the same misread the surrounding caveats exist to prevent.
MIN_WINDOWS_FOR_SUMMARY_TABLE = 3

TARGET = 80.0
REACH_THRESHOLDS = [40.0, 50.0, 60.0]
N_FRAMES = 30
HOURS_APART = 6.0

# on-model (nu=1, exact logistic) -- optimistic ceiling, not a fair test
_ON_MODEL_PARAMS = [
    (92, 0.05, 60), (88, 0.035, 80), (95, 0.07, 45), (90, 0.045, 70), (85, 0.03, 90),
    (93, 0.055, 55), (87, 0.04, 85), (96, 0.06, 65),
]
# off-model (nu=3, Richards/asymmetric) -- NOT one of growth.py's candidates
_OFF_MODEL_PARAMS = [
    (92, 0.05, 60), (88, 0.04, 75), (95, 0.065, 50), (90, 0.05, 65),
    (93, 0.045, 70), (89, 0.055, 55), (96, 0.04, 80),
]

STREAMS = [
    {"tag": f"on_model_{i}", "family": "on_model", "K": K, "r": r, "t0": t0, "nu": 1.0}
    for i, (K, r, t0) in enumerate(_ON_MODEL_PARAMS)
] + [
    {"tag": f"off_model_{i}", "family": "off_model", "K": K, "r": r, "t0": t0, "nu": 3.0}
    for i, (K, r, t0) in enumerate(_OFF_MODEL_PARAMS)
]


def _fake_sha(tag: str) -> str:
    return hashlib.sha256(tag.encode()).hexdigest()


def _richards(t, K, r, t0, nu):
    """Generalized logistic. nu=1 reduces to the exact logistic growth.py
    also fits (on_model streams); nu != 1 is asymmetric around the
    inflection and matches neither of growth.py's two candidate curves
    (off_model streams) — see module docstring."""
    return K / (1.0 + np.exp(-r * (t - t0))) ** (1.0 / nu)


def _true_crossing(K, r, t0, nu, target):
    if target >= K:
        return None
    f = lambda t: _richards(t, K, r, t0, nu) - target
    try:
        return float(brentq(f, t0 - 2000, t0 + 2000))
    except ValueError:
        return None


def _append_parquet(cache_dir: str, name: str, rows: list[dict]) -> None:
    os.makedirs(cache_dir, exist_ok=True)
    path = os.path.join(cache_dir, f"{name}.parquet")
    new_df = pd.DataFrame(rows)
    if os.path.exists(path):
        new_df = pd.concat([pd.read_parquet(path), new_df], ignore_index=True)
    new_df.to_parquet(path, index=False)


def _write_sequence(cache_dir, sequence_id, start, n_frames, hours_apart, K, r, t0, nu, crop_noise_sd, rng):
    """Writes one synthetic time-lapse sequence straight into cache_dir's
    parquet tables, matching culture.cache.Cache's on-disk schema exactly —
    culture/replay.py only ever reads these tables (never touches pixels),
    so a synthetic cache exercises its real code path, same fixture pattern
    as demo/flask_timeline.py and tests/test_replay.py."""
    base = pd.Timestamp(start)
    images_rows, conf_rows, logits_rows, quality_rows = [], [], [], []
    for i in range(n_frames):
        t_hours = i * hours_apart
        sha = _fake_sha(f"{sequence_id}-{i}")
        full_pct = float(np.clip(_richards(t_hours, K, r, t0, nu), 0.1, 99.9))
        images_rows.append({
            "image_sha256": sha, "dataset": "backtest_fixture", "source_path": f"/fake/{sha}.png",
            "sequence_id": sequence_id, "frame_idx": i,
            "timestamp": (base + pd.Timedelta(hours=t_hours)).isoformat(),
            "height": 256, "width": 256, "bit_depth": "uint8", "normalization": "grayscale_imread",
        })
        conf_rows.append({
            "image_sha256": sha, "crop_spec": "full", "model_name": "seg", "model_version": "cpsam_v2",
            "pct": full_pct, "confidence": 0.8, "extra": json.dumps({}),
        })
        for k in range(4):
            crop_pct = float(np.clip(full_pct + rng.normal(0, crop_noise_sd), 0, 100))
            conf_rows.append({
                "image_sha256": sha, "crop_spec": f"crop_f0.25_s1_k{k}", "model_name": "seg",
                "model_version": "cpsam_v2", "pct": crop_pct, "confidence": 0.75,
                "extra": json.dumps({"frac": 0.25}),
            })
        logits_rows.append({
            "image_sha256": sha, "crop_spec": "full", "model_name": "qc", "model_version": "qc_effnetb0_v1",
            "logits": json.dumps([float(x) for x in rng.normal(0, 2, 4)]),
        })
        quality_rows.append({
            "blur_laplacian_var": float(rng.uniform(300, 700)),
            "exposure_mean": float(rng.uniform(126, 130)),
            "uniformity_block_std": float(rng.uniform(0.2, 0.7)),
            "image_sha256": sha, "model_name": "quality", "model_version": "quality_v1",
        })
    _append_parquet(cache_dir, "images", images_rows)
    for name, rows in [("confluency", conf_rows), ("logits", logits_rows), ("quality", quality_rows)]:
        _append_parquet(cache_dir, name, rows)


def run_backtest(work_dir: str, seed: int = 0, n_boot: int = 200) -> pd.DataFrame:
    rows = []
    for stream in STREAMS:
        K, r, t0, nu = stream["K"], stream["r"], stream["t0"], stream["nu"]
        true_t80 = _true_crossing(K, r, t0, nu, TARGET)
        if true_t80 is None or not (0 <= true_t80 <= (N_FRAMES - 1) * HOURS_APART * 1.5):
            continue  # crossing outside a reasonable window for this frame budget -- skip, don't force it

        for repositioning, crop_noise_sd in [("with_repositioning", 5.0), ("without_repositioning", 0.5)]:
            sequence_id = f"seq_{stream['tag']}_{repositioning}"
            cache_dir = os.path.join(work_dir, f"cache_{sequence_id}")
            rng = np.random.default_rng(seed)
            _write_sequence(cache_dir, sequence_id, start="2026-01-01T00:00:00Z",
                             n_frames=N_FRAMES, hours_apart=HOURS_APART, K=K, r=r, t0=t0, nu=nu,
                             crop_noise_sd=crop_noise_sd, rng=rng)
            cache = Cache(cache_dir)

            visits = build_replay_visits(cache, sequence_id, lineage_id=f"L_{sequence_id}",
                                          segment_id=f"S_{sequence_id}", flask_id="backtest-flask", seed=seed)
            visits.sort(key=lambda v: v["timestamp"])

            for reach in REACH_THRESHOLDS:
                prefix = []
                for v in visits:
                    prefix.append(v)
                    if v["confluency_mean"] >= reach:
                        break
                else:
                    continue  # never reached this threshold within the replay -- skip

                result = fit_growth(prefix, target_pct=TARGET, seed=seed, n_boot=n_boot)
                row = {
                    "stream": stream["tag"], "family": stream["family"], "repositioning": repositioning,
                    "reach_threshold": reach, "n_visits_in_prefix": len(prefix),
                    "true_t80_hours": true_t80, "status": result.status,
                    "t_star_status": result.t_star_status,
                    "predicted_t80_hours": np.nan, "abs_error_hours": np.nan,
                    "interval_lo": np.nan, "interval_hi": np.nan, "covered": np.nan,
                }
                if result.status == "OK" and result.t_star_status == "REACHED":
                    row["predicted_t80_hours"] = result.t_star_hours
                    row["abs_error_hours"] = abs(result.t_star_hours - true_t80)
                    if result.t_star_interval_hours is not None:
                        lo, hi = result.t_star_interval_hours
                        row["interval_lo"], row["interval_hi"] = lo, hi
                        row["covered"] = float(lo <= true_t80 <= hi)
                rows.append(row)

    return pd.DataFrame(rows)


def summarize(df: pd.DataFrame) -> pd.DataFrame:
    resolved = df[df["abs_error_hours"].notna()]
    return (
        resolved.groupby(["family", "repositioning"])
        .agg(
            n_windows=("abs_error_hours", "size"),
            median_abs_error_hours=("abs_error_hours", "median"),
            coverage_pct=("covered", lambda s: 100.0 * s.mean()),
        )
        .reset_index()
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--work-dir", default=None)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--n-boot", type=int, default=200)
    args = ap.parse_args()

    work_dir = args.work_dir or tempfile.mkdtemp(prefix="growth_backtest_")
    os.makedirs(RESULTS_DIR, exist_ok=True)

    df = run_backtest(work_dir, seed=args.seed, n_boot=args.n_boot)
    df.to_csv(os.path.join(RESULTS_DIR, "growth_backtest.csv"), index=False)

    summary = summarize(df)
    table_summary = summary[summary["n_windows"] >= MIN_WINDOWS_FOR_SUMMARY_TABLE]
    omitted = summary[summary["n_windows"] < MIN_WINDOWS_FOR_SUMMARY_TABLE]

    lines = [
        "# Growth model backtest (SYNTHETIC — harness correctness check, not real prediction accuracy)",
        "",
        "**No real C2C12/CTC sequences are cached yet** (culture/replay.py's own docstring: the real",
        "Slice 1b cache has sequence_id/frame_idx unset for every row). Every stream below is a",
        "hand-generated synthetic curve replayed through the real culture/replay.py + culture/growth.py",
        "code path — this checks the fitting/prediction/bootstrap code is correct, not real prediction",
        "accuracy. `on_model` streams are exact logistics (an optimistic ceiling — growth.py's own",
        "logistic candidate is literally the generating function); `off_model` streams are asymmetric",
        "(Richards, nu=3) curves that are **not** one of growth.py's two candidates — the fairer check.",
        "",
        "**This table must not be quoted as the §12 claims-policy backtest sentence until re-run on",
        "real cached sequences.** Also note: `n_windows` counts (stream x reach_threshold) pairs, not",
        "independent trials -- the three reach thresholds for one stream/repositioning often resolve to",
        "the same or an overlapping visit prefix, so at these small counts the coverage % is a rough",
        "signal, not a calibrated estimate (that needs many more, less-correlated streams -- real",
        "sequences, once cached, would supply that naturally).",
        "",
        "**`on_model` + `with_repositioning` coverage is well below 90% -- this is a known limit, not a",
        "bug:** growth.py's bootstrap resamples residuals *within* the AIC-chosen model only; it never",
        "lets a resample prefer the other model, so it misses model-selection uncertainty. That's exactly",
        "what dominates here -- on sparse, noisy early-reach prefixes, logistic vs Gompertz AIC often ties",
        "(diagnosed directly: one such prefix scored -10.56 vs -11.55, an effective coin flip), and",
        "whichever wins can extrapolate the same short prefix to a meaningfully different T*. See",
        "culture/growth.py's own docstring for the same caveat.",
        "",
        f"Groups with fewer than {MIN_WINDOWS_FOR_SUMMARY_TABLE} resolved windows are omitted from this",
        "table (one window is one data point -- a median/coverage % over 1-2 of them isn't a summary",
        "statistic); they're still in the CSV, not hidden, just not presented as if they were.",
        "",
        "| family | repositioning | n_windows | median abs error (h) | 90% interval coverage |",
        "|---|---|---|---|---|",
    ]
    for _, r in table_summary.iterrows():
        lines.append(
            f"| {r['family']} | {r['repositioning']} | {int(r['n_windows'])} | "
            f"{r['median_abs_error_hours']:.1f} | {r['coverage_pct']:.0f}% |"
        )
    lines.append("")
    if len(omitted):
        lines.append(
            f"Omitted for n_windows < {MIN_WINDOWS_FOR_SUMMARY_TABLE} (see growth_backtest.csv for the raw rows): "
            + "; ".join(f"{r['family']}/{r['repositioning']} (n={int(r['n_windows'])})" for _, r in omitted.iterrows())
        )
        lines.append("")

    md_path = os.path.join(RESULTS_DIR, "growth_backtest.md")
    with open(md_path, "w") as f:
        f.write("\n".join(lines))

    print("\n".join(lines))
    print(f"\nwrote {os.path.join(RESULTS_DIR, 'growth_backtest.csv')}")
    print(f"wrote {md_path}")


if __name__ == "__main__":
    main()
