#!/usr/bin/env python3
"""
Dry run of the console Space's live Analyze (ZeroGPU), from outside, the way
a viewer sees it: each precomputed example's image is uploaded and analyzed
live on the Space, the wall time per Analyze is measured (GPU attach
included), and the live record is compared with the stored example.

    python scripts/space_dry_run.py [--space LongGrainRice/cultureqc-console] [--out results/live_latency_zerogpu.md]

Signed in with the local Hugging Face token, so the GPU time is charged to the
owner's ZeroGPU quota (as on the call, signed in on huggingface.co), not the
smaller anonymous one. Each Analyze appends a record to the Space's session
chain, as pressing the button does.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import statistics
import sys
import time
from datetime import datetime, timezone

from gradio_client import Client, handle_file
from huggingface_hub import HfApi, get_token

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from demo import precomputed  # noqa: E402


def live_record(results_html: str) -> dict:
    m = re.search(r'<pre class="audit-json">(.*?)</pre>', results_html, re.S)
    if not m:
        raise RuntimeError("no audit record in the Analyze output: " + re.sub(r"<[^>]+>", " ", results_html)[:300])
    return json.loads(html.unescape(m.group(1)))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--space", default="LongGrainRice/cultureqc-console")
    ap.add_argument("--out", default="results/live_latency_zerogpu.md")
    args = ap.parse_args()

    runtime = HfApi().get_space_runtime(args.space)
    sha = HfApi().space_info(args.space).sha
    client = Client(args.space, token=get_token(), verbose=False)

    rows = []
    for i, ex in enumerate(precomputed.load()):
        client.predict(handle_file(precomputed.image_path(ex)), api_name="/on_upload")
        t0 = time.perf_counter()
        out = client.predict(ex["cell_line"], ex["target_confluency"], api_name="/run_analysis")
        wall = time.perf_counter() - t0
        rec = live_record(out[2] if isinstance(out, (list, tuple)) else out)
        stored_conf = ex["confluency"]
        rows.append({
            "key": ex["id"], "order": i + 1, "wall_s": wall,
            "pct_live": rec["confluency_pct"], "pct_stored": stored_conf["pct"],
            "conf_live": rec["confluency_confidence"], "conf_stored": stored_conf["confidence"],
            "flag_live": rec.get("anomaly_flag"), "flag_stored": ex["anomaly"].get("flag"),
            "action_live": rec["recommended_action"], "action_stored": ex["action"],
        })
        r = rows[-1]
        print(f"{r['key']}: {wall:.1f} s, {r['pct_live']:.2f}% vs {r['pct_stored']:.2f}%, "
              f"{r['action_live']} vs {r['action_stored']}", flush=True)

    same = sum(r["flag_live"] == r["flag_stored"] and r["action_live"] == r["action_stored"] for r in rows)
    warm = [r["wall_s"] for r in rows[1:]]
    lines = [
        f"# Live latency and parity: console Space on ZeroGPU ({args.space})",
        "",
        f"Generated by `scripts/space_dry_run.py` on {datetime.now(timezone.utc).isoformat(timespec='seconds')}, "
        f"Space commit `{sha[:10]}`, hardware `{runtime.hardware}`. Signed in (the owner's ZeroGPU quota). "
        "Wall time is one Analyze as the viewer waits for it, measured from the client: "
        "network, queue, GPU attach and the pipeline.",
        "",
        "| # | example | wall time (s) | confluency live / stored (%) | confidence live / stored | anomaly flag live / stored | action live / stored |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| {r['order']} | {r['key']} | {r['wall_s']:.2f} | {r['pct_live']:.2f} / {r['pct_stored']:.2f} | "
                     f"{r['conf_live']:.3f} / {r['conf_stored']:.3f} | {r['flag_live']} / {r['flag_stored']} | "
                     f"{r['action_live']} / {r['action_stored']} |")
    lines += [
        "",
        f"First Analyze of this run: {rows[0]['wall_s']:.2f} s.",
        f"Median of the rest: {statistics.median(warm):.2f} s (n = {len(warm)}).",
        f"Anomaly flag and action the same as stored: {same} of {len(rows)} examples.",
        "",
    ]
    with open(args.out, "w") as f:
        f.write("\n".join(lines))
    print("wrote", args.out)


if __name__ == "__main__":
    main()
